server:
  port: 8081
  servlet:
    context-path: /api/supplier

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://mysql:3306/supplier
    username: root
    password: 1234
