server:
  port: 8081
  servlet:
    context-path: /api/supplier

spring:
  rabbitmq:
    # todo: fix docker containers interconnection
    host: 10.135.6.28
    port: 5672
    username: guest
    password: guest