server:
  port: 8081
  servlet:
    context-path: /api/supplier

spring:
  rabbitmq:
    # todo: fix docker containers interconnection
    host: 192.168.1.2
    port: 5672
    username: guest
    password: guest